theme: jekyll-theme-primer
title: Alex Queudot - Software Engineer | Android, iOS, Flutter
description: I'm passionate about crafting exceptional mobile experiences, scaling systems, and delivering reliable, high-quality applications.
twitter:
  username: alqueraf
  card: summary
logo: /images/aq-logo.png
image:
  path: /images/phone-logo.png
  width: 96
  height: 96
social:
  links:
    - https://www.linkedin.com/in/alexqueudot
    - https://medium.com/@alqueraf
    - https://twitter.com/alqueraf
    - https://www.instagram.com/alqueraf
    - https://github.com/alqueraf
plugins:
  - jekyll-seo-tag
whitelist:
  - jekyll-seo-tag
