theme: jekyll-theme-primer
title: Alex Queudot - Software Engineer & Educator
description: Software Engineer, Android & iOS, Consultant, Tech Lead, Professor. I'm passionate about creating exceptional mobile experiences, scaling systems, and delivering reliable, high-quality applications.
twitter:
  username: alqueraf
  card: summary
logo: /images/aq-logo.png
social:
  links:
    - https://www.linkedin.com/in/alexqueudot
    - https://medium.com/@alqueraf
    - https://twitter.com/alqueraf
    - https://www.instagram.com/alqueraf
    - https://github.com/alqueraf
plugins:
  - jekyll-seo-tag
whitelist:
  - jekyll-seo-tag
