theme: jekyll-theme-primer
title: [Alex Queudot - Mobile Engineer & Educator]
description: [Alex Queudot. Android & iOS Developer. Building beautiful experiences for mobile. Teaching App Development at University in Barcelona. World Traveller.]