name: Latest appstores data workflow
on:
  schedule: # Run workflow automatically
    - cron: '20 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-apps:
    name: Update this repo's README with latest appstores data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alqueraf/appstores-feed-action@master
        with:
          app_ids: "lr.globalcitizen.com, 1372884614, org.avenew.activist, 990655529, de.entwickler.tutorials.app, 1535102177"