name: Latest appstores data workflow
on:
  schedule: # Run workflow automatically
    - cron: '20 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-apps:
    name: Update this repo's README with latest appstores data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alqueraf/appstores-feed-action@master
        with:
          appstore_ids: "123321,321123"
          playstore_ids: "org.example1,org.example2"