name: Latest goodreads workflow
on:
  schedule: # Run workflow automatically
    - cron: "15 0 * * *" # Runs Every: (Hour: 0 * * * *). (Day: 0 0 * * *))
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-goodreads:
    name: Update this repo's README with latest activity from goodreads
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GOODREADS"
          commit_message: "Updated readme with the latest goodreads data"
          committer_username: goodreads-read-bot
          committer_email: goodreads-read-bot@example.com
          feed_list: "https://www.goodreads.com/review/list_rss/40277231?shelf=read&sort=date_added&order=d"
          max_post_count: 5
