name: Latest linkedin workflow
on:
  schedule: # Run workflow automatically
    - cron: "25 0 * * *" # Runs Every: (Hour: 0 * * * *). (Day: 0 0 * * *))
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest linkedin activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "LINKEDIN"
          commit_message: "Updated readme with the latest linkedin activity"
          committer_username: linkedin-activity-bot
          committer_email: linkedin-activity-bot@example.com
          # https://www.linkedin.com/in/alexqueudot
          feed_list: "https://fetchrss.com/rss/67267c90d05f8cb6e00bdc6467267c82bb33446ff20b0273.xml"
          max_post_count: 3
          item_exec: |
            post.title = post.title.replaceAll(/(?:\\r\\n|\\r|\\n)/g,' ');
            post.title = post.title.replaceAll('\n',' ');
            post.title = post.title.replaceAll('\r\n',' ');
