name: Latest twitter workflow
on:
  schedule: # Run workflow automatically
    - cron: "20 0 * * *" # Runs Every: (Hour: 0 * * * *). (Day: 0 0 * * *))
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITTER"
          commit_message: "Updated readme with the latest tweets"
          committer_username: twitter-tweets-bot
          committer_email: twitter-tweets-bot@example.com
          feed_list: "https://rss.app/feeds/QzWxE84qlPYSRyat.xml"
          max_post_count: 3
          item_exec: |
            post.title = post.title.replace(/(?:\\r\\n|\\r|\\n)/g,' ');
